package Exceptions.Seminars;

public class 1 {
    
}
//public class Main {
//    public static void main(String[] args) {
//        // Node node = new node();
//        //ArithmeticException exception = new ArithmeticException()
//
//        try {
//            System.out.println("message1");
//            throw  new ArithmeticException("MESSAGE");
//          //  System.out.println("message2");
//        }catch (ArithmeticException exception) {
//            System.out.println("message3");
//            System.out.println(exception);
//            System.out.println(exception.getMessage());
//            exception.printStackTrace();
//        }
//        System.out.println("message4");
//    }
//}
//        int num[] = {4, 8, 16, 32, 64, 128, 256, 512};
//        int num2[] = {2, 0, 4, 4, 0, 8};
//        try { //Внешний
//            for (int i = 0; i < num.length; i++) {
//                try { //Внутренний
//                    System.out.println(num[i] + " / " +
//                            num2[i] + " = " +
//                            num[i] / num2[i]);
//                } catch (ArrayIndexOutOfBoundsException exception) {
//                    System.out.println("ERROR !!! Array !!!");
//                }
//
//            }
//        } catch (ArithmeticException exceptionexception) {
//            System.out.println("Division 0 !!!");
//
//        }
//    }
//}

//        int nums[] = new int[4];
//
//        try {
//            System.out.println("message1");
//            nums[8] = 10;
//            System.out.println("message2");
//        } catch (Exception exception){
//            System.out.println("SuperMessage");
//        }
//        System.out.println("message5");
//    }